namespace Zomp.SyncMethodGenerator;

/// <summary>
/// Contains the source of the attributes the generator adds to every compilation.
/// </summary>
public static class SourceGenerationHelper
{
    internal const string CreateSyncVersionAttributeSource = $$"""
// <auto-generated/>
namespace Zomp.SyncMethodGenerator
{
#if !SYNC_METHOD_GENERATOR_DISABLE_ATTRIBUTE_GENERATION
    /// <summary>
    /// An attribute that can be used to automatically generate a synchronous version of an async method(s). Must be used in or on a partial type.
    /// </summary>
    /// <remarks>
    /// This attribute can be applied to both methods and types.
    /// When applied to a containing type (class, struct, record, or interface), all eligible async methods will have their sync version generated
    /// unless <see cref="SkipSyncVersionAttribute"/> is applied to the individual methods.
    /// </remarks>
    [System.AttributeUsage(
        System.AttributeTargets.Method |
        System.AttributeTargets.Class |
        System.AttributeTargets.Struct |
        System.AttributeTargets.Interface,
        AllowMultiple = false,
        Inherited = false)]
    internal class {{SyncMethodSourceGenerator.CreateSyncVersionAttribute}} : System.Attribute
    {
        /// <summary>
        /// Gets or sets a value indicating whether "#nullable enable" directive will be omitted from generated code. False by default.
        /// </summary>
        public bool {{SyncMethodSourceGenerator.OmitNullableDirective}} { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether <see cref="System.IProgress{T}"/> parameters will be preserved in the generated code. False by default.
        /// </summary>
        public bool {{SyncMethodSourceGenerator.PreserveProgress}} { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether <see cref="System.Threading.CancellationToken"/> parameters will be preserved in the generated code. False by default.
        /// </summary>
        public bool {{SyncMethodSourceGenerator.PreserveCancellationToken}} { get; set; }
    }
#endif
}
""";

    internal const string SkipSyncVersionAttributeSource = $$"""
// <auto-generated/>
namespace Zomp.SyncMethodGenerator
{
#if !SYNC_METHOD_GENERATOR_DISABLE_ATTRIBUTE_GENERATION
    /// <summary>
    /// Skips sync version generation of a method when <see cref="CreateSyncVersionAttribute"/> is applied to a containing type.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal class {{SyncMethodSourceGenerator.SkipSyncVersionAttribute}} : System.Attribute
    {
    }
#endif
}
""";
}
