//HintName: Test.Test.FileSystem.WriteAllTextAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class FileSystem
{
    public virtual void WriteAllText(string path, string contents) { }
}
