//HintName: Test.Test.FileSystem.ReadAllTextAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class FileSystem
{
    public virtual string ReadAllText(string path) => "";
}
