//HintName: Tests.StreamExtensions.ext.CopyAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Tests;
public static partial class StreamExtensions
{
    /// <param name="stream">The stream to copy from.</param>
    extension(global::System.IO.Stream stream)
    {
        /// <summary>
        /// Copies the stream.
        /// </summary>
        /// <param name="destination">Where to copy to.</param>
        /// <param name="progress">Progress reporter.</param>
        public void Copy(
            global::System.IO.Stream destination,
            global::System.IProgress<int>? progress = null
        ) => stream.CopyTo(destination);
    }
}
