//HintName: Zomp.SyncMethodGenerator.IntegrationTests.EntityFrameworkQuery_0f26cde8.QueryableExtensionAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Microsoft.EntityFrameworkCore;

    public partial class EntityFrameworkQueryableExtensions
    {
        public int QueryableExtension(global::Microsoft.EntityFrameworkCore.DbContext dbContext)
        {
            var dbSet = dbContext.Set<object>();
            if (global::System.Linq.Queryable.Any(dbSet))
            {
                return global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteDelete(dbSet);
            }
            
            return 0;
        }
    }
}
