//HintName: Callers.StreamCallers.ext.CopyAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Callers
{
    using Helpers;

    public static partial class StreamCallers
    {
        extension(global::System.IO.Stream stream)
        {
            public void Copy(
                global::System.IO.Stream destination,
                global::System.IProgress<int>? progress = null
            ) =>
                global::Helpers.StreamExtensions.WriteTo(
                        stream,
                        destination,
                        4096,
                        progress: progress);
        }
    }
}
