//HintName: Tests.Class.WhereGreaterThan.g.cs
// <auto-generated/>
#nullable enable
namespace Tests;
static partial class Class
{
    public global::System.Collections.Generic.IEnumerable<T> WhereGreaterThan(this global::System.Collections.Generic.IEnumerable<T> source, T threshold, int dummy)
    {
        foreach (var item in source)
        {
            if (item > threshold)
            {
                yield return item;
            }
        }
    }
}
