//HintName: Tests.Class.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Tests;
partial class Class
{
    public void Method()
    {
        _ = ((global::System.Func<global::Tests.Bar?,global::Tests.Bar?>)((param)=>(object?)param == null?(global::Tests.Bar?)null: global::Tests.BarExtension.DoSomething(param)))(global::Tests.Bar.Create());
    }
}
