//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Extensions.HasGeneric2ExtensionAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Drawing;
using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Extensi.ons123;

    partial class Extensions
    {
        public static void HasGeneric2Extension(object o)
        {
            var z = global::Extensi.ons123.MyExtensionClass.TryGetValue<global::System.Drawing.Point, global::System.Drawing.PointF>(o, out var _, out var _1);
        }
    }
}
