//HintName: Callers.StreamCallers.ext.CopyAndDrainAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Callers
{
    public static partial class StreamCallers
    {
        extension(global::System.IO.Stream stream)
        {
            public void CopyAndDrain(global::System.IO.Stream destination)
            {
                stream.CopyTo(destination);
                global::Helpers.StreamExtensions.Drain(stream);
            }
        }
    }
}
