//HintName: Callers.StreamCallers.ext.DrainTwiceAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Callers
{
    public static partial class StreamCallers
    {
        extension(global::System.IO.Stream stream)
        {
            public void DrainTwice() =>
                global::Helpers.StreamExtensions.Drain(stream,                         1024)                    ;
        }
    }
}
