//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Caller.CallAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Microsoft.EntityFrameworkCore;

    public partial class Caller
    {
        public int Call(global::Microsoft.EntityFrameworkCore.DbContext dbContext)
        {
            var dbSet = dbContext.Set<object>();
            var any = global::System.Linq.Queryable.Any(dbSet);
            var list = global::System.Linq.Enumerable.ToList(dbSet);
            return any ? list.Count : global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteDelete(dbSet);
        }
    }
}
