//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Extensions.HasGenericExtensionAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Drawing;
using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Extensi.ons123;

    partial class Extensions
    {
        public static void HasGenericExtension(object o)
        {
            var z = global::Extensi.ons123.MyExtensionClass.TryGetValue<global::System.Drawing.Point>(o, out var item);
        }
    }
}
