//HintName: Tests.Class.WhereGreaterThan.g.cs
// <auto-generated/>
#nullable enable
namespace Tests;
static partial class Class
{
    public static global::System.Collections.Generic.IEnumerable<T> WhereGreaterThan<T>(this global::System.Collections.Generic.IEnumerable<T> source, T threshold, int dummy)
        where T : global::System.Numerics.INumber<T>
    {
        foreach (var item in source)
        {
            if (item > threshold)
            {
                yield return item;
            }
        }
    }
}
