//HintName: Tests.Class.ext.WhereGreaterThan.g.cs
// <auto-generated/>
#nullable enable
namespace Tests;
static partial class Class
{
    extension<T>(global::System.Collections.Generic.IEnumerable<T> source)
        where T : global::System.Numerics.INumber<T>
    {
        public global::System.Collections.Generic.IEnumerable<T> WhereGreaterThan(T threshold)
        {
            foreach (var item in source)
            {
                if (item > threshold)
                {
                    yield return item;
                }
            }
        }
    }
}
