//HintName: Zomp.SyncMethodGenerator.IntegrationTests.EntityFrameworkQueryableExtensions.QueryableExtensionAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    public partial class EntityFrameworkQueryableExtensions
    {
        public bool QueryableExtension(global::System.Linq.IQueryable<object> source)
        {
            return global::System.Linq.Queryable.Any(source);
        }
    }
}
