//HintName: A.Long.Enough.Namespace.To.Make.The.Generated.File.Name.Exceed.What.Is.Rea_89a6d38e.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace A.Long.Enough.Namespace.To.Make.The.Generated.File.Name.Exceed.What.Is.Reasonable;
public partial class OuterClass
{
    public partial class InnerClass
    {
        public void Method()
        {
        }
    }
}
