//HintName: A.Long.Enough.Namespace.To.Make.The.Generated.File.Name.Exceed.What.Is.R_79dbcd19.MethodAsync_2.g.cs
// <auto-generated/>
#nullable enable
namespace A.Long.Enough.Namespace.To.Make.The.Generated.File.Name.Exceed.What.Is.Reasonable;
public partial class OuterClass
{
    public partial class InnerClass
    {
        public void Method(int i)
        {
        }
    }
}
