//HintName: Test.Stuff.StuffAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    void Stuff(global::System.Collections.Generic.IEnumerable<int> range)
    {
        global::System.Collections.Generic.IEnumerator<int> e = range.GetEnumerator();
        try
        {
            while (e.MoveNext()) global::System.Console.Write(e.Current + " ");
        }
        finally { if (e != null) e.Dispose(); }
    }
}
