//HintName: ReplaceWithAttribute.g.cs
// <auto-generated/>
namespace Zomp.SyncMethodGenerator
{
    /// <summary>
    /// An attribute that can be used to specify the synchronous type a parameter should be converted into .
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Parameter)]
    internal class ReplaceWithAttribute : System.Attribute
    {
        public virtual CollectionTypes Variations { get; set; }
    }
}
