//HintName: Tests.Class.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Tests;
internal partial class Class
{
    public void Method(global::System.IO.Stream stream)
    {
        Do(global::Tests.MemoryExtensions.GetStuff(6).Span);
    }
}
