//HintName: N1.Class.FillAsync.g.cs
// <auto-generated/>
#nullable enable
namespace N1
{
    partial class Class
    {
        void Fill(global::System.Span<global::N2.C1.C2.Accelerometer> accelerometers)
        {
            global::N2.C1.C2.Accelerometer a = new(1, 2, 3);
            accelerometers[0] = a;
        }
    }
}
