//HintName: Test.MyClass.MethodAsync.g.cs
// <auto-generated/>
namespace Test;
partial class MyClass
{
    [global::System.ObsoleteAttribute]
    public void Method()
    {
        string f = null;
    }
}
