//HintName: Test.MyClass.MethodAsync.g.cs
// <auto-generated/>
namespace Test;
partial class MyClass
{
    public void Method(global::System.IO.Stream stream)
    {
        _ = ((object)stream == null ? (global::System.IO.Stream)null : global::Test.Extension.DoSomething(stream));
    }
}
