//HintName: Test.WithNullableDisabled.DoNothingAsync.g.cs
// <auto-generated/>
#nullable disabled
namespace Test;
internal partial class WithNullableDisabled
{
    public void DoNothing(string l)
    {
        l = null;
    }
}
