//HintName: Test.Record.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial record Record
{
    public void Method() => global::System.Threading.Thread.Sleep(1000);
}
