//HintName: Test.RecordStruct.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial record struct RecordStruct
{
    public readonly void Method() => global::System.Threading.Thread.Sleep(1000);
}
