//HintName: Test.Struct.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial struct Struct
{
    public readonly void Method() => global::System.Threading.Thread.Sleep(1000);
}
