//HintName: Test.SimpleMacro.ExecAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class SimpleMacro
{
    public void Exec()
    {
#if SYMBOL
        throw new global::System.InvalidOperationException("Some exception");
#endif
    }
}
