//HintName: Test.Stuff.ExecAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class Stuff
{
    public void Exec()
    {
        global::System.Console.Write("Done");
    }
}
