//HintName: Test.DisposeTest.DisposeAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class DisposeTest
{
    public void Dispose(object? obj)
    {

        if (obj is global::System.IDisposable disposable)
        {
            disposable.Dispose();
            return;
        }

        if (obj is global::System.IAsyncDisposable)
        {
            throw new global::System.InvalidOperationException("Cannot dispose an async disposable in sync-only mode.");
        }
    }
}
