//HintName: Test.Stuff.ExecAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class Stuff
{
    public void Exec()
    {
        if (true)
        {
            throw new InvalidOperationException("Some exception");
        }
    }
}
