//HintName: Test.SimpleMacro.ExecAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class SimpleMacro
{
    public void Exec()
    {
#if SYMBOL1
        ArgumentNullException.ThrowIfNull(source);
#elif SYMBOL2
        ArgumentNullException.ThrowIfNull(source);
#else
        global::System.ArgumentNullException.ThrowIfNull(source);
#endif
    }
}
