//HintName: Test.Extensions.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal static partial class Extensions
{
    internal static void Method(global::System.Collections.Generic.IEnumerable<int> enumerable)
    {
        using System.Collections.Generic.IEnumerator<int> enumerator = enumerable.GetEnumerator();
    }
}
