//HintName: Test.Extensions.GetConfiguredAsyncEnumerator.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal static partial class Extensions
{
    public static System.Collections.Generic.IEnumerator<int> GetConfiguredEnumerator(global::System.Collections.Generic.IEnumerable<int> enumerable)
    {
        return enumerable.GetEnumerator();
    }
}
