//HintName: System.Class.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace System;
public partial class Class
{
    public void Method()
    {
        global::System.Security.Cryptography.CryptographicException z = null!;
    }
}
