//HintName: Test.Class.MethodAsync.g.cs
// <auto-generated/>
#nullable enable

using static System.Data.ConnectionState;

namespace Test;
partial class Class
{
    public void Method()
    {
        _ = global::System.Data.ConnectionState.Closed is global::System.Data.ConnectionState.Closed;
    }
}
