//HintName: Test.Class.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Class
{
    public void Method() 
    {
        semaphore.Wait();

        try
        {
            global::System.Threading.Thread.Sleep(100);
        }
        finally
        {
            semaphore.Release();
        }
    }
}
