//HintName: Test.Stuff.InternalExampleAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static int InternalExample(global::System.IO.Stream stream)
    {
        static void LocalFunc()
        {
        }

        LocalFunc();
    }
}
