//HintName: Test.Stuff.WriteAllTextAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    public static void WriteAllText(string file, string contents)
    {
        global::System.IO.File.WriteAllText(file, contents);
    }
}
