//HintName: Test.Stuff.GetArrayOfTAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static global::System.Collections.Generic.IList<T> GetArrayOfT<T>() where T: new()
    {
        return new T[] { new T() };
    }
}
