//HintName: Zomp.SyncMethodGenerator.IntegrationTests.ExtensionMethods.ZeroParamsAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Extensi.ons123;

    partial class ExtensionMethods
    {
        public static void ZeroParams(object o) => global::Extensi.ons123.MyExtensionClass.SomeMethod(o);
    }
}
