//HintName: Test.Class.ReadSomeBytesAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace Test;
public partial class Class
{
    public int ReadSomeBytes(global::System.IO.Stream stream)
    {
        var buffer = new byte[100];
        return stream.Read(buffer, 0, 100);
    }
}
