//HintName: M.B.DoSomethingAsync.g.cs
// <auto-generated/>
#nullable enable
namespace M
{
    using N;

    public partial class B
    {
        public void DoSomething()
        {
            _ = typeof(global::System.Collections.Generic.List<global::N.A>);
            global::System.Threading.Thread.Sleep(1);
        }
    }
}
