//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Stuff.CallWithIProgressAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Zomp.SyncMethodGenerator.IntegrationTests;
internal partial class Stuff
{
    public static void CallWithIProgress()
    {
        WithIProgress();
    }
}
