//HintName: Zomp.SyncMethodGenerator.IntegrationTests.ExtensionMethods.ZeroParamsAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    partial class ExtensionMethods
    {
        public static void ZeroParams(object o) => global::Extensi.ons123.MyExtensionClass.SomeMethod(o);
    }
}
