//HintName: Test.Class.ReadAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Class
{
    /// <summary>
    /// Reads a value.
    /// </summary>
    /// <param name="input">Where to read from.</param>
    /// <returns>A task.</returns>
    public void Read(global::System.IO.Stream input)
        => input.Flush();
}
