//HintName: Test.Stuff.InternalExampleAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static int InternalExample(global::System.IO.Stream stream)
    {
        static int Internal(global::System.IO.Stream stream)
        {
            var buf = new byte[1];
            return stream.Read(buf, 0, 1);
        }
        return Internal(stream);
    }
}
