//HintName: N1.C1.MethodAsync.g.cs
// <auto-generated/>
#nullable enable

using static N2.C2;

namespace N1
{
    public partial class C1
    {
        public void Method()
        {
            _ = global::N2.C2.OtherConst;
        }
    }
}
