//HintName: Test.Class.WrappedAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace Test;
public partial class Class
{
    /// <summary>
    /// A summary
    /// </summary>
    public void Wrapped() { }
}
