//HintName: Test.Stuff.DoItAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static void DoIt()
    {
        static int Local()
        {
            return 0;
        }

        _ = SomeMethod(Local);
    }
}
