//HintName: Test.Stuff.ForeachLoop.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class Stuff
{
    public static void ForeachLoop()
    {
        foreach (int i in new int[] { 1 })
        {
        }
    }
}
