//HintName: Test.GenericClass{T}.MethodAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class GenericClass<T>
{
    public void Method()
    {
        _ = global::Test.GenericClass<T>.Bar;
    }
}
