//HintName: Test.Stuff.WithAction.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static void WithAction(global::System.Action<Point, global::System.Collections.Generic.IEnumerable<global::System.Drawing.Point>>? action) { }
}
