//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Extensions.HasGenericExtensionAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    partial class Extensions
    {
        public static void HasGenericExtension(object o)
        {
            var z = global::Extensi.ons123.MyExtensionClass.TryGetValue<global::System.Drawing.Point>(o, out var item);
        }
    }
}
