//HintName: CreateSyncVersionAttribute.g.cs
// <auto-generated/>
namespace Zomp.SyncMethodGenerator
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public class CreateSyncVersionAttribute : System.Attribute
    {
    }
}