//HintName: NsOne.C1.C2.C3.C4.EmptyAsync.g.cs
// <auto-generated/>
#nullable enable
namespace NsOne
{
    public partial class C1
    {
        internal partial class C2
        {
            private protected partial class C3
            {
                private partial class C4
                {
                    void Empty()
                    {
                    }
                }
            }
        }
    }
}
