//HintName: Test.Stuff.TypeDeclarations.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class Stuff
{
    public static void TypeDeclarations()
    {
        string myStr;
        string myStrPredefined;
        global::System.Exception ex;
        short myShort;
        long myLong;
    }
}
