//HintName: Test.Class.WrappedAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Class
{
    /// <summary>
    /// A summary
    /// </summary>
    public void Wrapped() {}
}
