//HintName: Test.Stuff.GetColorAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public int GetColor(global::System.IO.FileAccess access = global::System.IO.FileAccess.Read)
        => 1;
}
