//HintName: Test.Stuff.MakeArray.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    private void MakeArray(byte[] sampleBytes)
    {
        global::System.Span<byte> mem = global::System.MemoryExtensions.AsSpan(sampleBytes, 0, 123);
        var arr = mem.ToArray();
    }
}
