//HintName: Test.Class.SendAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test
{
    public partial class Class
    {
        /// <summary>
        /// Sends a <see cref="StringBuilder"/> over a <see cref="Socket"/>.
        /// </summary>
        /// <param name="input">Where to read from.</param>
        public void Send(global::System.IO.Stream input)
            => input.Flush();
    }
}
