//HintName: M.B.DoSomethingAsync.g.cs
// <auto-generated/>
#nullable enable
namespace M
{
    public partial class B
    {
        public void DoSomething(object arg)
        {
            if (arg is global::System.Collections.Generic.List<global::N.A> lst)
            {
                global::System.Threading.Thread.Sleep(1);
            }
        }
    }
}
