//HintName: Test.Stuff.ReadAsMemoryAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    private void ReadAsMemory(global::System.IO.Stream stream, byte[] sampleBytes)
    {
        stream.Read(global::System.MemoryExtensions.AsSpan(sampleBytes, 0, 123));
    }
}
