//HintName: Test.Class.DelegateAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Class
{
    internal static void Delegate()
    {
        static void LocalFunc()
        {
        }

        var zz = () => LocalFunc();
        zz();
    }
}
