//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Extensions.HasGeneric2ExtensionAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    partial class Extensions
    {
        public static void HasGeneric2Extension(object o)
        {
            var z = global::Extensi.ons123.MyExtensionClass.TryGetValue<global::System.Drawing.Point, global::System.Drawing.PointF>(o, out var _, out var _1);
        }
    }
}
