//HintName: Test.Stuff.GetIntAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static int GetInt()
    {
        return new[] { 1, 2 }[0];
    }
}
