//HintName: Test.Class{T}.FooAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class Class<T>
{
    public void Foo(global::System.Linq.IQueryable<string> source)
    {
        global::System.Linq.Enumerable.ToList(source);
    }
}
