//HintName: Test.Class{T}.FooAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
internal partial class Class<T>
{
    public void Foo()
    {
       global::Test.CustomThread.Sleep(1000);
    }
}
