namespace Zomp.SyncMethodGenerator.Cloning;

/// <summary>
/// Builds the source file a cloned method is emitted in, declaring again, as partial, each
/// namespace and type the original method was nested in.
/// </summary>
internal static class ClonedMethodSource
{
    /// <summary>
    /// Builds the source file for a method.
    /// </summary>
    /// <param name="method">The method.</param>
    /// <returns>Text of the file.</returns>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases", Justification = "Only deal with selected SyntaxKinds")]
    public static string Generate(ClonedMethod method)
    {
        static string GetKeyword(SyntaxKind sk) => sk switch
        {
            SyntaxKind.PublicKeyword => "public",
            SyntaxKind.InternalKeyword => "internal",
            SyntaxKind.PrivateKeyword => "private",
            SyntaxKind.SealedKeyword => "sealed",
            SyntaxKind.ProtectedKeyword => "protected",
            SyntaxKind.StaticKeyword => "static",
            SyntaxKind.AbstractKeyword => "abstract",
            _ => throw new InvalidOperationException($"{sk} is not supported"),
        };

        var location = method.Location;

        // Handle namespaces
        var sbBegin = new StringBuilder();
        var sbEnd = new StringBuilder();
        var i = 0;

        if (!location.IsNamespaceFileScoped)
        {
            foreach (var @namespace in location.Namespaces)
            {
                var indent = new string(' ', 4 * i);
                _ = sbBegin.Append($$"""
{{indent}}namespace {{@namespace}}
{{indent}}{

""");
                _ = sbEnd.Insert(0, $$"""
{{indent}}}

""");
                ++i;
            }
        }

        // Directives which were written inside the namespace are emitted inside it, at the
        // innermost level. One which names a namespace relatively still resolves from there.
        foreach (var @using in location.InnerUsings)
        {
            _ = sbBegin.Append($$"""
{{new string(' ', 4 * i)}}{{@using}}

""");
        }

        if (!location.InnerUsings.IsEmpty)
        {
            _ = sbBegin.Append("""


""");
        }

        // Handle classes
        foreach (var parent in location.Parents)
        {
            var indent = new string(' ', 4 * i);

            var modifiers = string.Join(string.Empty, parent.Modifiers.Select(z => GetKeyword((SyntaxKind)z) + " "));
            var parentType = parent.MethodParent switch
            {
                MethodParent.Class => "class",
                MethodParent.Interface => "interface",
                MethodParent.Struct => "struct",
                MethodParent.Record => "record"
                + parent.ClassOrStructKeyword.Kind() switch
                {
                    SyntaxKind.StructKeyword => " struct",
                    SyntaxKind.ClassKeyword => " class",
                    _ => string.Empty,
                },
                _ => throw new NotImplementedException("Cannot handle the parent of the method"),
            };

            var classDeclarationLine = $"{modifiers}partial {parentType} {parent.ParentName}{(parent.TypeParameterListSyntax.IsEmpty ? string.Empty
                : "<" + string.Join(", ", parent.TypeParameterListSyntax) + ">")}";

            _ = sbBegin.Append($$"""
{{indent}}{{classDeclarationLine}}
{{indent}}{

""");
            _ = sbEnd.Insert(0, $$"""
{{indent}}}

""");
            ++i;
        }

        var sbOuterUsings = new StringBuilder();
        foreach (var @using in location.OuterUsings)
        {
            if (sbOuterUsings.Length == 0)
            {
                // Separates the directives from the header above them.
                _ = sbOuterUsings.Append("""



""");
            }

            _ = sbOuterUsings.Append($$"""
{{@using}}

""");
        }

        var beforeNamespace = $"""
// <auto-generated/>{(method.DisableNullable ? string.Empty : """

#nullable enable
""")}{sbOuterUsings}
""";

        return location.IsNamespaceFileScoped ? $$"""
{{beforeNamespace}}
namespace {{location.Namespaces.First()}};
{{sbBegin}}{{new string(' ', 4 * i)}}{{method.Implementation.Trim()}}
{{sbEnd}}
"""
            : $$"""
{{beforeNamespace}}
{{sbBegin}}{{new string(' ', 4 * i)}}{{method.Implementation.Trim()}}
{{sbEnd}}
""";
    }
}
