//HintName: Test.Stuff.HalfCheckSumAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    static int HalfCheckSum(global::System.Span<byte> buffer, global::System.IO.Stream stream)
        => ChecksumRead(buffer, stream) / 2;
}
