//HintName: Test.Stuff.GetPointAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static global::System.Drawing.Point[] GetPoint()
    {
        return new[] { new global::System.Drawing.Point(1, 2) };
    }
}
