//HintName: Test.Stuff.WriteAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    static void Write(global::System.ReadOnlySpan<byte> buffer, Stream stream)
        => stream.Write(buffer);
}
