//HintName: Zomp.SyncMethodGenerator.IntegrationTests.OverloadsNS.ReadAsMemoryAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Zomp.SyncMethodGenerator.IntegrationTests;
internal partial class OverloadsNS
{
    void ReadAsMemory(global::System.IO.Stream stream, byte[] sampleBytes)
        => stream.Read(global::System.MemoryExtensions.AsSpan(sampleBytes, 0, 123));
}
