//HintName: Test.Stuff.GetArrayOfTAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
partial class Stuff
{
    public static global::System.Collections.Generic.LinkedListNode<global::System.Drawing.Point>[] GetArrayOfT<T>() where T : new()
    {
        return new global::System.Collections.Generic.LinkedListNode<global::System.Drawing.Point>[] { };
    }
}
