//HintName: NsOne.NsTwo.NsThree.NsFour.MultipleNamespaces.EmptyAsync.g.cs
// <auto-generated/>
#nullable enable
namespace NsOne
{
    namespace NsTwo.NsThree
    {
        namespace NsFour
        {
            public partial class MultipleNamespaces
            {
                void Empty()
                {
                }
            }
        }
    }
}
