//HintName: Test.Stuff.ReadAsMemoryAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
public partial class Stuff
{
    private void ReadAsMemory(Stream stream, byte[] sampleBytes)
        => stream.Read(sampleBytes.AsSpan(0, 123));
}
